# Generated by Django 2.2.1 on 2019-06-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
