# Generated by Django 2.2.1 on 2019-06-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Portpolio',
        ),
    ]
