# Generated by Django 2.2.1 on 2019-06-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190626_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portpolio',
            new_name='Portfolio',
        ),
    ]
