# Generated by Django 2.2.1 on 2019-07-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190630_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='images',
        ),
    ]
