# Generated by Django 2.2.1 on 2019-07-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190703_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='images',
        ),
    ]
