# Generated by Django 2.2.1 on 2019-07-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_portfolio_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='images',
            field=models.ImageField(default=1, upload_to='./images/'),
            preserve_default=False,
        ),
    ]
